### PR TITLE
Fix country code detection.

### LINKED ISSUE #76: qemu-x86_64": library "libdl.so" not found
I tried to run Arch x86_64 on my aarch64 Termux, but received this error:
`CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/qemu-x86_64": library "libdl.so" not found: needed by main executable`
with libdl.so being present in arch64 directory.

There were also error messages during installation:
`usr/bin/newuidmap: Cannot restore extended attributes on this system`
`bsdtar: Error exit delayed from previous errors.`
`Signal generated in 'proot _PREPROOT_ setupTermuxArch necessaryfunctions.bash'; Cannot complete task;`

### PR DESCRIPTION
**Pull request by yakovlevegor**
Fixes #76. Gets the first country code from command return.

### CODE REVIEW

**Comment by SDRausty** [comment]
Thank you @yakovlevegor;  Please share your retest results.

**Comment by SDRausty** [comment]
The USECACHEDIR option accessible in `knownconfigurations.bash` can assist in debugging by caching the install system files for later reinstall: [`USECACHEDIR=1           ##  change to 0 to use cache dir;  When changed to 0 this installation script uses a cache directory defined in `necessaryfunctions.bash` that is used as to cache all installation files in order to save wireless bandwidth.  Variable `KEEP=1`  should be changed to 0 also in order to keep the downloaded image and to populate the cache. The downloaded image and md5 files should be moved to CACHEDIR in order to avoid subsequent redownloading of these files for reinstalling the entire system.`](https://github.com/TermuxArch/TermuxArch/blob/master/knownconfigurations.bash#L14)

**Comment by yakovlevegor** [comment]
My fork doesn't work. Will try upstream repository in a moment.

**Comment by yakovlevegor** [comment]
Unfortunately it's the same. Trying to debug the issue.

**Comment by yakovlevegor** [comment]
Screenshot_20220207-092958_Termux

There indeed seems to be an error on line 556 `_RUNFINISHSETUP_printf` in **necessaryfunctions.bash**, after fixing by adding a newline I suddenly get a segmentation fault in **archlinuxconfig.bash**.

**Comment by yakovlevegor** [comment]
> Screenshot_20220207-092958_Termux
> 
> There indeed seems to be an error on line 556 `_RUNFINISHSETUP_printf` in **necessaryfunctions.bash**, after fixing by adding a newline I suddenly get a segmentation fault in **archlinuxconfig.bash**.

Oh, sorry. This is false, I left a session open between reinstalls.

**Comment by yakovlevegor** [comment]
> > Screenshot_20220207-092958_Termux
> > There indeed seems to be an error on line 556 `_RUNFINISHSETUP_printf` in **necessaryfunctions.bash**, after fixing by adding a newline I suddenly get a segmentation fault in **archlinuxconfig.bash**.
> 
> Oh, sorry. This is false, I left a session open between reinstalls.

No, unfortunately I get segfault even after killing all sessions.

**Comment by yakovlevegor** [comment]
Screenshot_20220207-095458_Termux

Though the segfault I am getting now is a bit different.

**Comment by SDRausty** [comment]
Thank you very much again in assisting @yakovlevegor;  Line 556 that began with [_RUNFINISHSETUP_printf](https://github.com/TermuxArch/TermuxArch/commit/72d39591c08bd9828b953bc59b51deb871f045ad#diff-6c93d067c2851bd7b9d9c05fd58d368b0b46f8e7f728e6eff7da276d6ce9fea8L556) should begin with [printf](https://github.com/TermuxArch/TermuxArch/commit/72d39591c08bd9828b953bc59b51deb871f045ad#diff-6c93d067c2851bd7b9d9c05fd58d368b0b46f8e7f728e6eff7da276d6ce9fea8R556).  Commit https://github.com/TermuxArch/TermuxArch/commit/72d39591c08bd9828b953bc59b51deb871f045ad repairs line 556 in file `necessaryfunctions.bash`.

**Comment by yakovlevegor** [comment]
Screenshot_20220207-101035_Termux

Saying prior, and I think it's safe to say it now, your commit fixed it all.

**Comment by SDRausty** [comment]
You found bugs, congratulations;  Your clear and hard work debugging assisted greatly in expediting fixes.  Thank you 🎵 🎶

**Pull request merged**
