### PR TITLE
Change to sudoers.d and correct wheel

### PR DESCRIPTION
**Pull request by petkar**
- Changed `usermod "\$1" -g wheel` to `usermod "\$1" -aG wheel`

- Added password prompt on creating a user `passwd "\$1"`

- Changed default from `sudoers` file to file in `sudoers.d` directory as editing the sudoers file directly is not recommended

### CODE REVIEW

**Comment by SDRausty** [comment]
This is not necessary as all users created with `addauser` are without passwords:
```
$ grep -n passwd *h
archlinuxconfig.bash:18:                sed -i "s/\$1:x/\$1:/g" /etc/passwd
```
This enables `sudo` on the fly now.  This pull request could be a useful if it were tied to setup configurations via options.

**Comment by petkar** [comment]
Do consider the other changes, you may leave the passed part unchanged.

**Comment by SDRausty** [comment]
Lines #L16&&#L17 seem okay.

**Comment by SDRausty** [comment]
This wants accounting too:
```
$ grep -n sudoers *h                                                                
archlinuxconfig.bash:17:                [[ -f /etc/sudoers ]] && printf "%s\\n" "\$1 ALL=(ALL) ALL" >> /etc/sudoers
```

**Comment by petkar** [comment]
Okay, dropped set new passwd prompt.

**Comment by SDRausty** [comment]
Thank you ; integrated with https://github.com/TermuxArch/TermuxArch/commit/6ccecba4e41706913bbb476aa09a045d572de912  there still are errors

**Comment by petkar** [comment]
Could you give a detailed report the errors?

**Comment by petkar** [comment]
Also, changing the default behaviour of sudo to ALL=(ALL) NOPASSWD: ALL could be a security risk because it wouldn't be clear when scripts are using root. The ALL=(ALL) ALL option works perfectly and is the expected behaviour. Users should change it otherwise if necessary. Any perticular reason you enforced this option as default?

**Comment by petkar** [comment]
And it's only necessary to either use the sudoers file or the sudoers.d directly, not both. It is recommended to edit the sudoers file only using visudo, therefore adding the user file in the visudo.d directory should be preferred.

**Comment by SDRausty** [comment]
This https://github.com/TermuxArch/TermuxArch/commit/cac564fae6d321c053c8bcc74cd280e4e2772b44 commit adds passwordless `su` support.

**Comment by SDRausty** [comment]
>  ALL=(ALL) NOPASSWD: ALL could be a security risk 

>  the sudoers file or the sudoers.d directly, not both

Done with this  the sudoers file or the sudoers.d directly, not both commit.

**Comment by SDRausty** [comment]
> detailed report the errors

Asking for passwords when running `su`, which is no longer the case with this https://github.com/TermuxArch/TermuxArch/commit/fee2ef5ce28a886def576119513bcde5351a4406 commit.

**Pull request merged**
