### PR TITLE
Fix xorg not starting by correcting owner

### PR DESCRIPTION
**Pull request by petkar**
I realized that refreshing caused some change in ownership in the home directory of the user, The fix were these commands which should make the user the owner of their home directory after a refresh (which in turn should stop breaking xauth). But please edit and correct the format appropriately.

### CODE REVIEW

**Comment by SDRausty** [comment]
Thank you @petkar integrated with https://github.com/TermuxArch/TermuxArch/commit/db638048352c8220e01a05ebe85e18fdc11eaf1f

**Comment by SDRausty** [comment]
It appears this merge has generated this error:
```
usermod: no changes

 TermuxArch WARNING:  Generated script signal 4 near or at line number 76 by `startarch c "usermod -u $UID $USER 2>/dev/null"`!
```
While `setupTermuxArch.bash r` and `setupTermuxArch.bash refresh` work as expected, `setupTermuxArch.bash re` does not. 

| option | purpose |
| -- | -- |
|`setupTermuxArch.bash r` | quick root user refresh |
| `setupTermuxArch.bash re` | quick root and users refresh with locale-gen |
|  `setupTermuxArch.bash refresh` | full root and users refresh with locale-gen and keys |

**Comment by SDRausty** [comment]
> has generated this error:

resolved with https://github.com/TermuxArch/TermuxArch/commit/7dcb973a21bec8f23ec621d31a6441c7b701b20c

**Comment by SDRausty** [comment]
@petkar can you please submit a pull request similar to this one regarding:

> Edit : Note :
> 
> ```
>    		startarch c "usermod -u $UID $USER 2>/dev/null"
>    			startarch c "groupmod -g $GID $USER 2>/dev/null"
> ```


>  as for `startarch c "chown -R $USER:$USER /home/$USER"` it should be run as the user and not root. Please edit it to execute as user.

https://github.com/SDRausty/TermuxArch/issues/205#issuecomment-668163644

**Comment by elswerky** [comment]
I want to run arch by non root user I created and open arch in termux on this user not root by default

If anyone can help me

**Pull request merged**
