### PR TITLE
Fix country code detection.

### PR DESCRIPTION
**Pull request by yakovlevegor**
Fixes country code detection by filtering commas from `getprop gsm.operator.iso-country` value.

### CODE REVIEW

**Comment by yakovlevegor** [comment]
fixes #76

**Comment by SDRausty** [comment]
Thank you @yakovlevegor;  Can you rewrite this pr with variable substitution instead of using the command `sed` please.

**Comment by SDRausty** [comment]
> pr with variable substitution

`f "=\"" *sh | f \/\/ | f \{`
>1:7:archlinuxconfig.bash:281:[[ -n "\${1:-}" ]] && { [[ "\${1//-}" = [\/]* ]] || [[ "\${1//-}" = [?]* ]] || [[ "\${1//-}" = [Hh]* ]] ; } && { printf '\e[1;32m%s\n' "Help for '\${0##*/}':" && TSFILE="(\$(grep '##\ ' "\$0"))" && printf '\e[0;32m%s\e[1;32m\n%s\n' "\$(for HL in "\${TSFILE[@]}" ; do cut -d\) -f1 <<< "\${HL//###/ }" | cut -f 2 ; done )" "Help for '\${0##*/}': DONE" ; exit ; }
2:13:archlinuxconfig.bash:324:THRESHOLD="\${THRESHOLD//-}"
3:39:archlinuxconfig.bash:739:BASENAME="\${BASENAME#*//}" # strip before double slash
4:98:getimagefunctions.bash:51:NLCMIRR="${NLCMI//\`}"
5:99:getimagefunctions.bash:52:NLCMIRROR="${NLCMIRR//\'}"
7:144:knownconfigurations.bash:132:PROOTSTMNTU="${PROOTSTMNT//HOME=\/root/HOME=\/home\/\$2}"
8:145:knownconfigurations.bash:133:PROOTSTMNTU="${PROOTSTMNTU//-0 }"
9:146:knownconfigurations.bash:134:PROOTSTMNTU="${PROOTSTMNTU//-w \/root/-w \/home\/\$2}" # PRoot user string with link2symlink option enabled
10:147:knownconfigurations.bash:135:PROOTSTMNTEU="${PROOTSTMNTU//--link2symlink }" # PRoot user string with link2symlink option disabled
11:148:knownconfigurations.bash:136:PROOTSTMNT="${PROOTSTMNT//-i \"\$2:wheel\" }" # PRoot root user string
13:199:necessaryfunctions.bash:220:MINOR_REVISION="$(sed 's/[^0-9]*//g' <<< "${TMPKERN:0:3}")"
16:223:necessaryfunctions.bash:624:ULANGUAGE="${LANGIN[i]//-/_}"
20:280:printoutstatements.bash:247:PRINTROOTDIR="$(printf "%s" "${ROOTDIR%/}"|sed 's#//*#/#g')"
23:307:setupTermuxArch:396:INSTALLDIR="$(printf "%s\\n" "$HOME/${ROOTDIR%/}" | sed 's#//*#/#g')"
24:308:setupTermuxArch:399:DARCH="$(printf "%s\\n" "${ROOTDIR%/}"|sed 's#//*#/#g')" # ${@%/} removes trailing slash
28:347:setupTermuxArch:793:STIME="$(cat /proc/sys/kernel/random/uuid)" && STIME="${STIME//-}" && STIME="${STIME//[[:alpha:]]}" && STIME="${STIME:0:3}"
31:383:setupTermuxArch.bash:396:INSTALLDIR="$(printf "%s\\n" "$HOME/${ROOTDIR%/}" | sed 's#//*#/#g')"
32:384:setupTermuxArch.bash:399:DARCH="$(printf "%s\\n" "${ROOTDIR%/}"|sed 's#//*#/#g')" # ${@%/} removes trailing slash
36:423:setupTermuxArch.bash:793:STIME="$(cat /proc/sys/kernel/random/uuid)" && STIME="${STIME//-}" && STIME="${STIME//[[:alpha:]]}" && STIME="${STIME:0:3}"
39:459:setupTermuxArch.sh:396:INSTALLDIR="$(printf "%s\\n" "$HOME/${ROOTDIR%/}" | sed 's#//*#/#g')"
40:460:setupTermuxArch.sh:399:DARCH="$(printf "%s\\n" "${ROOTDIR%/}"|sed 's#//*#/#g')" # ${@%/} removes trailing slash
44:499:setupTermuxArch.sh:793:STIME="$(cat /proc/sys/kernel/random/uuid)" && STIME="${STIME//-}" && STIME="${STIME//[[:alpha:]]}" && STIME="${STIME:0:3}"

I would like to assist in this topic, and your help is requested;  If you choose to, @yakovlevegor please update `sed` to variable substitution after using `git pull` as variable substitution is more efficient by far as it is built into to shell.  Hopefully this information will help in expediting this superfluous comma topic quicker.

**Comment by yakovlevegor** [comment]
> > pr with variable substitution
> 
> `f "=\"" *sh | f \/\/ | f \{`
> 
> > 1:7:archlinuxconfig.bash:281:[[ -n "${1:-}" ]] && { [[ "${1//-}" = [/]* ]] || [[ "${1//-}" = [?]* ]] || [[ "${1//-}" = [Hh]* ]] ; } && { printf '\e[1;32m%s\n' "Help for '${0##_/}':" && TSFILE="($(grep '##\ ' "$0"))" && printf '\e[0;32m%s\e[1;32m\n%s\n' "$(for HL in "${TSFILE[@]}" ; do cut -d) -f1 <<< "${HL//###/ }" | cut -f 2 ; done )" "Help for '${0##_/}': DONE" ; exit ; }
> > 2:13:archlinuxconfig.bash:324:THRESHOLD="${THRESHOLD//-}"
> > 3:39:archlinuxconfig.bash:739:BASENAME="${BASENAME#_//}" # strip before double slash
> > 4:98:getimagefunctions.bash:51:NLCMIRR="${NLCMI//`}"
> > 5:99:getimagefunctions.bash:52:NLCMIRROR="${NLCMIRR//'}"
> > 7:144:knownconfigurations.bash:132:PROOTSTMNTU="${PROOTSTMNT//HOME=/root/HOME=/home/$2}"
> > 8:145:knownconfigurations.bash:133:PROOTSTMNTU="${PROOTSTMNTU//-0 }"
> > 9:146:knownconfigurations.bash:134:PROOTSTMNTU="${PROOTSTMNTU//-w /root/-w /home/$2}" # PRoot user string with link2symlink option enabled
> > 10:147:knownconfigurations.bash:135:PROOTSTMNTEU="${PROOTSTMNTU//--link2symlink }" # PRoot user string with link2symlink option disabled
> > 11:148:knownconfigurations.bash:136:PROOTSTMNT="${PROOTSTMNT//-i "$2:wheel" }" # PRoot root user string
> > 13:199:necessaryfunctions.bash:220:MINOR_REVISION="$(sed 's/[^0-9]_//g' <<< "${TMPKERN:0:3}")"
> > 16:223:necessaryfunctions.bash:624:ULANGUAGE="${LANGIN[i]//-/_}"
> > 20:280:printoutstatements.bash:247:PRINTROOTDIR="$(printf "%s" "${ROOTDIR%/}"|sed 's#//_#/#g')"
> > 23:307:setupTermuxArch:396:INSTALLDIR="$(printf "%s\n" "$HOME/${ROOTDIR%/}" | sed 's#//_#/#g')"
> > 24:308:setupTermuxArch:399:DARCH="$(printf "%s\n" "${ROOTDIR%/}"|sed 's#//_#/#g')" # ${@%/} removes trailing slash
> > 28:347:setupTermuxArch:793:STIME="$(cat /proc/sys/kernel/random/uuid)" && STIME="${STIME//-}" && STIME="${STIME//[[:alpha:]]}" && STIME="${STIME:0:3}"
> > 31:383:setupTermuxArch.bash:396:INSTALLDIR="$(printf "%s\n" "$HOME/${ROOTDIR%/}" | sed 's#//_#/#g')"
> > 32:384:setupTermuxArch.bash:399:DARCH="$(printf "%s\n" "${ROOTDIR%/}"|sed 's#//_#/#g')" # ${@%/} removes trailing slash
> > 36:423:setupTermuxArch.bash:793:STIME="$(cat /proc/sys/kernel/random/uuid)" && STIME="${STIME//-}" && STIME="${STIME//[[:alpha:]]}" && STIME="${STIME:0:3}"
> > 39:459:setupTermuxArch.sh:396:INSTALLDIR="$(printf "%s\n" "$HOME/${ROOTDIR%/}" | sed 's#//_#/#g')"
> > 40:460:setupTermuxArch.sh:399:DARCH="$(printf "%s\n" "${ROOTDIR%/}"|sed 's#//*#/#g')" # ${@%/} removes trailing slash
> > 44:499:setupTermuxArch.sh:793:STIME="$(cat /proc/sys/kernel/random/uuid)" && STIME="${STIME//-}" && STIME="${STIME//[[:alpha:]]}" && STIME="${STIME:0:3}"
> 
> I would like to assist in this topic, and your help is requested; If you choose to, @yakovlevegor please update `sed` to variable substitution after using `git pull` as variable substitution is more efficient by far as it is built into to shell. Hopefully this information will help in expediting this superfluous comma topic quicker.

I'm still working on my solution, updating bash exp.

**Pull request closed without merging**
