### PR TITLE
Modify AUR support

### PR DESCRIPTION
**Pull request by petkar**
- Prevent execution as root user
- Added support to fakeroot-tcp to apply patch automatically and build without `--no-prepare` option
- Removed `--noprepare` option from yay as it was redundant and builds successfully without it and removed `go` package as it was a build dependency and eats up about half a gig of disk space. Could be installed manually if necessary.
- Made makepkg update proof

### CODE REVIEW

**Comment by SDRausty** [comment]
Thank you ; integrated with https://github.com/TermuxArch/TermuxArch/commit/6ccecba4e41706913bbb476aa09a045d572de912  there still are errors

**Comment by SDRausty** [comment]
This https://github.com/TermuxArch/TermuxArch/commit/d35e19374aa9a70ab0981ba55d7927bebbd1ff5c commit adds more support for _ADDfbindprocversion_ but it still does mot build and install with one tap.

**Comment by SDRausty** [comment]
This https://github.com/TermuxArch/TermuxArch/commit/d35e19374aa9a70ab0981ba55d7927bebbd1ff5c commit adds more support for `_ADDmakefakeroot-tcp_` and it finally does build and install with one tap.

**Comment by SDRausty** [comment]
The command `makeyay.bash` does not succeed:
```
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by petkar** [comment]
Why is that so? This is unexpected

**Comment by SDRausty** [comment]
The last line before `makeyay.bash` exits is:
```
==> Starting build()...                                                                              
go build -v -trimpath -mod=readonly -modcacherw -ldflags '-s -w -extldflags "-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now" -X "main.yayVersion=10.0.3" -X "main.localePath=/usr/share/locale/"' -buildmode=pie -o yay!
```
 Building `yay` worked a short while ago.  Probably an error somewhere in `makeyay.bash`.

**Comment by petkar** [comment]
Does it fail normally with `makepkg -si` or only with the script?

**Comment by SDRausty** [comment]
Building `yay` by hand was successful [here](https://github.com/TermuxArch/TermuxArch/issues/14#issuecomment-669670599), but not any success yet with `makeyay.bash`.

**Comment by petkar** [comment]
I just tried `makeyay.bash` and it build successfully. I did `setupTermuxArch.sh refresh` `re` and `r` and restarted termux. It worked correctly.

**Comment by SDRausty** [comment]
Thank you for confirming.  I found out why I ran into problems building `yay`, `go` did not install completely because of lack of space on device.  After reinstalling `go`, `makeyay.bash` is working as expected.

**Pull request merged**
